### PR TITLE
Fix flux ci

### PR DESCRIPTION
**Pull request by Samir-Rashid**
im testing ci

### CODE REVIEW

**Comment by Samir-Rashid** [comment]
@enjhnsn2 Remaining errors before this PR is good to go

Rust problems:

```rust
error: mutable borrow from immutable input(s)
  --> kernel/src/platform/chip.rs:41:22
   |
41 |     fn mpu(&self) -> &mut Self::MPU;
   |                      ^^^^^^^^^^^^^^
   |
```

Flux problems:

```rust
error[E0999]: cannot access fields of opaque struct `flux_ptr::FluxPtr`
  --> flux_support/src/flux_ptr.rs:19:9
   |
19 | /         FluxPtr {
20 | |             inner: value as *mut u8,
21 | |         }
   | |_________^

error[E0999]: cannot access fields of opaque struct `flux_ptr::FluxPtr`
  --> flux_support/src/flux_ptr.rs:34:9
   |
34 |         ptr.inner as u8
   |         ^^^^^^^^^

error[E0999]: cannot access fields of opaque struct `flux_ptr::FluxPtr`
  --> flux_support/src/flux_ptr.rs:49:10
   |
49 |         (self.inner as usize) % rhs
   |          ^^^^^^^^^^

error[E0999]: cannot access fields of opaque struct `flux_ptr::FluxPtr`
  --> flux_support/src/flux_ptr.rs:57:21
   |
57 |             inner: (self.inner as usize + rhs) as *mut u8,
   |                     ^^^^^^^^^^

```

**Comment by enjhnsn2** [comment]
For the imports that use std `std::ops::Rem` and `std::slice::Iter`, those both have `core` counterparts, can you just replace them with `core::ops::Rem` and `core::slice::Iter`?

**Comment by enjhnsn2** [comment]
As for the flux issues: if those functions aren't passing right because you need to access `inner`, just mark them `flux_rs::trusted` for now

**Comment by Samir-Rashid** [comment]
I have addressed your comments. I believe this PR is done and more work should be moved to further development. Only needs to wait on me to rebase the ring_buffer changes.

Remaining work:
1. Resolve mpu ownership error
2. A bunch of legitmate Flux errors have cropped up
3. A new Flux internal compiler error. I will diagnose and submit an issue.

**Comment by enjhnsn2** [comment]
What legitimate Flux errors have popped up? The only flux changes (I think) should be providing implementations for trusted functions, which shouldn't raise errors.

**Comment by enjhnsn2** [comment]
Once we resolve the above issues I'll merge

**Comment by Samir-Rashid** [comment]
There are only overflow errors.

**Pull request merged**
